version: "3.1"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/client/node_modules
      - ./client:/app/client/
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: web-app
    tty: true
  api:
    image: express-api
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8000:8000"
    tty: true
networks:
  backend:
    driver: bridge
