version: "3.1"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  server:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=db
    ports:
      - 3333:3333
    command: yarn --cwd ./server start:dev
    depends_on:
      - db
    tty: true
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/client/node_modules
      - ./client:/app/client/
    ports:
      - '3000:3000'
    restart: on-failure
    tty: true
